- name: Register Catalog database into DBRC
  ibm.ibm_zos_ims.ims_dbrc:
    command:
      - INIT.DB DBD(DFSCD000) SHARELVL(3) TYPHALDB OLRCAP
      - INIT.PART DBD(DFSCD000) PART(DFSCD01)
          DSNPREFX({{ USR_HLQ }}.DFSCD000)
          KEYSTRNG(X'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF') GENMAX(5)
      - INIT.DB DBD(DFSCX000) SHARELVL(3) TYPHALDB
      - INIT.PART DBD(DFSCX000) PART(DFSCX01)
          DSNPREFX({{ USR_HLQ }}.DFSCX000)
          KEYSTRNG(X'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF') GENMAX(5)
      - LIST.DB DBD(DFSCD000)
      - LIST.DB DBD(DFSCX000)
    steplib:
      - "{{ STEPLIB }}"
    dbd_lib: "{{ SYS_DBDLIB }}"
    recon1: "{{ RECON_1 }}"
    recon2: "{{ RECON_2 }}"
    recon3: "{{ RECON_3 }}"
  register: dbrc_output

- name: Display output
  ansible.builtin.debug:
    var: dbrc_output
