- name: List catalog content
  ibm.ibm_zos_core.zos_mvs_raw:
    program_name: DFSRRC00
    parm: DLI,DFSDDLT0,DFSCP000,,,,,,,,,,,Y,N,,,,,,,,,,,,'DFSDF={{ DFSDF_SUFFIX }}'
    dds:
      - dd_data_set:
          dd_name: STEPLIB
          data_set_name: "{{ STEPLIB }}"
          disposition: shr
      - dd_data_set:
          dd_name: DFSRESLB
          data_set_name: "{{ RESLIB }}"
          disposition: shr
      - dd_data_set:
          dd_name: PROCLIB
          data_set_name: "{{ USR_PROCLIB }}"
          disposition: shr
      - dd_data_set:
          dd_name: RECON1
          data_set_name: "{{ RECON_1 }}"
          disposition: shr
      - dd_data_set:
          dd_name: RECON2
          data_set_name: "{{ RECON_2 }}"
          disposition: shr
      - dd_data_set:
          dd_name: RECON3
          data_set_name: "{{ RECON_3 }}"
          disposition: shr
      - dd_data_set:
          dd_name: DFSVSAMP
          data_set_name: "{{ BUFFER_POOL_PARAMS }}"
          disposition: shr
      - dd_dummy:
          dd_name: IEFRDER
      - dd_concat:
          dd_name: IMS
          dds:
            - dd_data_set:
                data_set_name: "{{ SYS_DBDLIB }}"
                disposition: shr
            - dd_data_set:
                data_set_name: "{{ SYS_PSBLIB }}"
                disposition: shr
      - dd_output:
          dd_name: SYSUDUMP
          return_content:
            type: text
      - dd_output:
          dd_name: PRINTDD
          return_content:
            type: text
      - dd_input:
          dd_name: SYSIN
          content: | 
            S11 1 1 1 1   3       1                                                 
            L        GU                                                             
            EHF    OK                                                               
            L   0500 GN                                                             
    verbose: true
  register: catalog_content

- ansible.builtin.debug:
    var: catalog_content
